version: "2"
services:
  db:
    env_file:   
      - .env
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - djangonetwork

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/protracker
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge