# Generated by Django 4.0 on 2022-01-06 03:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbConnectionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latlng', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
