# Generated by Django 4.0 on 2022-01-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbConnectionApp', '0002_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='latlng',
            new_name='point',
        ),
    ]
