# Generated by Django 4.0 on 2022-01-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbConnectionApp', '0004_line_polygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locality',
        ),
    ]
