# Generated by Django 4.0 on 2022-01-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbConnectionApp', '0005_delete_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='parentID',
            field=models.CharField(default='', max_length=150),
        ),
    ]
