# Generated by Django 4.0 on 2022-01-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbConnectionApp', '0006_point_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='parentID',
            field=models.CharField(max_length=150),
        ),
    ]
