# Generated by Django 4.0 on 2022-01-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbConnectionApp', '0007_alter_point_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='parentID',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='polygon',
            name='parentID',
            field=models.CharField(default='', max_length=150),
        ),
    ]
