# Generated by Django 4.0 on 2022-01-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbConnectionApp', '0008_line_parentid_polygon_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='parentID',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='parentID',
            field=models.CharField(max_length=150),
        ),
    ]
